### ISSUE TITLE
Failed to load asset: .. Cause: Failed to load audio

### ISSUE THREAD

**Issue by saleebm** [AlmasB/FXGL-MobileApp#1]
Hello, I'm trying to convert my game into the android using your platform which I'm very satisfied with. I really appreciate the effort and work you've accomplished in this project. I am recieving an error at AssetLoader.kt:254, 721 and (FXGLAssets.kt:44) on my mobile when I launch the app. Strangely the error is ExceptionInInitializerError at FXGLUIFactory.kt:53, 32, and 37 which has to do with text and font caused by the failure to load asset: core/notification.wav Failure to load audio. My desktop version works great. 

The most important deviation I have from the sample you posted that may be resulting in the error is that I am using the dalvik sdk and the android application repository. I did try to use the javafxport plugin instead and remove the android application repository because it was incompatible with the java plugin, and the game worked fine. So the problem lies in there but I do not want to get rid of the application repository for android because my onscreen control pad depends on it. Now I've come far with this game and if I have to I will do what it takes to make it function. 

 I have used 0.4.4-snapshot and 0.5.0-snapshot as well as audio versions 0.0.2-snapshot and 0.0.2. I am using Gradle 4.6, and gradle 3.0.1 for the plugin. Also, I'm using SDK 26. I haven't tried to switch it to the version you're using in the examples but I will give it a try now and give an update as soon as I do so. Perhaps that could be an issue for compatibility of the audio service. 

Is there perhaps a temporary solution however for me to disable the audio services just to demo the game on my android until it functions? 

https://github.com/ms12r/GalaxyMonkey1000

**Comment by AlmasB** [comment]
Hi, without javafxports plugin the audio service won't find the android service provider, hence the issue. Perhaps you can find an example where javafxplugin can work with the repository, or maybe reimplement the on screen control via JavaFX?
