### ISSUE TITLE
Fatal exception occurred: java.nio.file.FileSystemException : /./profiles: Read-only file system

### ISSUE THREAD

**Issue by saleebm** [AlmasB/FXGL-MobileApp#2]
Hi, I'm not sure why I'm receiving this error code. The app launches and goes to the menu, I click new game, and then it freezes at initialization. I have tried disabling the menu, profiles, and developer mode through the settings configuration. I don't know if this is the reason my app is not launching but it is the only message I receive in ADB. It did previously work in a very trimmed down version and I've tried to rework the changes I've made with no success. I am still going about that now so if anything changes, I'll update here.

I am using the 0.50 SNAPSHOT and I was able to make my own gamepad so I do have the javafxports mobile plugin now. I did try to go back to 0.44 SNAPSHOT and I still received the same error message. Is there anything I could do or try? I've exhausted my options. Thank you so much. 

EDIT:
I did a clean/rebuild, it worked temporarily, then now is failing with same error code. Cleaning it isn't doing it for me anymore. I've tried retracing my steps by going back to the code that worked and it doesn't work anymore. 

By the way, when you set the app width and height do you use FXGL.getApp().getWidth() or FXGL.getAppWidth()? 

https://github.com/ms12r/GalaxyMonkeyX

**Comment by ms12r** [comment]
Wow so I did a clean/build and it no longer gave me this error.

**Comment by saleebm** [comment]
Ok, I found the problem stems from enabling the menu in the game settings.

**Comment by AlmasB** [comment]
I see. Yes that would make sense. Menus require profiles, which use the
file system. The file system impl is different on mobiles. There’s an open
issue for this, but it’ll take some time to carefully integrate both. I’m
hoping to get it done for 0.5.1

**Comment by AlmasB** [comment]
@ms12r menus are now supported on mobile using 0.5.1-SNAPSHOT
